import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from config import *


class ReportGenerator:

    def __init__(self):

        print("✓ PDF Report Generator Ready")

        os.makedirs("reports", exist_ok=True)

        self.styles = getSampleStyleSheet()

        self.title_style = self.styles["Heading1"]
        self.title_style.alignment = TA_CENTER

        self.heading_style = self.styles["Heading2"]

        self.normal_style = self.styles["BodyText"]
            # =====================================================
    # GENERATE PDF REPORT
    # =====================================================

    def generate(self, report, analytics, decision):

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        pdf_path = os.path.join(
            "reports",
            f"SynapseAI_Report_{timestamp}.pdf"
        )

        doc = SimpleDocTemplate(pdf_path)

        elements = []

        # =====================================================
        # COVER PAGE
        # =====================================================

        elements.append(
            Paragraph(
                "🚦 SYNAPSE AI",
                self.title_style
            )
        )

        elements.append(
            Paragraph(
                "Smart Traffic Management System",
                self.heading_style
            )
        )

        elements.append(Spacer(1, 0.30 * inch))

        elements.append(
            Paragraph(
                "<b>AI Powered Traffic Analysis & Signal Optimization</b>",
                self.normal_style
            )
        )

        elements.append(Spacer(1, 0.20 * inch))

        elements.append(
            Paragraph(
                f"<b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
                self.normal_style
            )
        )

        elements.append(Spacer(1, 0.35 * inch))

        elements.append(
            Paragraph(
                """
This report was automatically generated by <b>Synapse AI</b>.

The system uses the YOLOv8 object detection model together with
AI-based traffic analysis to estimate congestion, recommend
green signal duration, evaluate traffic efficiency,
and calculate environmental impact.

The objective is to reduce congestion,
minimize waiting time,
and improve smart city traffic management.
                """,
                self.normal_style
            )
        )

        elements.append(Spacer(1, 0.40 * inch))
                # =====================================================
        # TRAFFIC ANALYSIS SUMMARY
        # =====================================================

        elements.append(
            Paragraph(
                "Traffic Analysis Summary",
                self.heading_style
            )
        )

        elements.append(Spacer(1, 0.15 * inch))

        vehicle_table = [

            ["Vehicle Type", "Count"],

            ["Cars", report["Cars"]],

            ["Buses", report["Buses"]],

            ["Trucks", report["Trucks"]],

            ["Motorcycles", report["Motorcycles"]],

            ["Bicycles", report["Bicycles"]],

            ["Persons", report["Persons"]],

            ["Total Vehicles", report["Total Vehicles"]]

        ]

        table = Table(vehicle_table, colWidths=[3.5*inch, 2*inch])

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0,0), (-1,0), colors.darkblue),

                ("TEXTCOLOR", (0,0), (-1,0), colors.white),

                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                ("ALIGN", (0,0), (-1,-1), "CENTER"),

                ("GRID", (0,0), (-1,-1), 1, colors.black),

                ("BACKGROUND", (0,1), (-1,-1), colors.beige),

                ("BOTTOMPADDING", (0,0), (-1,0), 10)

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.30 * inch))

        # =====================================================
        # AI DECISION SUMMARY
        # =====================================================

        decision_table = [

            ["Parameter", "Value"],

            ["Traffic Density", report["Traffic Density"]],

            ["Traffic Load Score", report["Traffic Load Score"]],

            ["Congestion (%)", report.get("Congestion (%)", "N/A")],

            ["Priority Level", report.get("Priority Level", "N/A")],

            ["Recommended Green Time", f"{report['Recommended Green Time']} sec"],

            ["AI Decision", decision["Reason"]]

        ]

        decision_tbl = Table(
            decision_table,
            colWidths=[3.5*inch, 2.5*inch]
        )

        decision_tbl.setStyle(

            TableStyle([

                ("BACKGROUND", (0,0), (-1,0), colors.green),

                ("TEXTCOLOR", (0,0), (-1,0), colors.white),

                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                ("GRID", (0,0), (-1,-1), 1, colors.black),

                ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),

                ("ALIGN", (0,0), (-1,-1), "CENTER"),

                ("BOTTOMPADDING", (0,0), (-1,0), 10)

            ])

        )

        elements.append(decision_tbl)

        elements.append(Spacer(1, 0.35 * inch))
                # =====================================================
        # ENVIRONMENTAL ANALYTICS
        # =====================================================

        elements.append(
            Paragraph(
                "Environmental Analytics",
                self.heading_style
            )
        )

        elements.append(Spacer(1, 0.15 * inch))

        analytics_table = [

            ["Metric", "Value"],

            ["Estimated Fuel Saved",
             f"{analytics['Estimated Fuel Saved (L)']} L"],

            ["Estimated CO₂ Reduction",
             f"{analytics['Estimated CO₂ Reduction (kg)']} kg"],

            ["Estimated Waiting Time",
             f"{analytics['Estimated Waiting Time (sec)']} sec"],

            ["Traffic Efficiency",
             f"{analytics['Traffic Efficiency (%)']} %"],

            ["Congestion Index",
             analytics["Congestion Index"]],

            ["Average Delay Per Vehicle",
             f"{analytics['Average Delay Per Vehicle (sec)']} sec"],

            ["Sustainability Score",
             analytics["Sustainability Score"]],

            ["Smart City Index",
             analytics["Smart City Index"]],

            ["AI Performance",
             analytics["AI Performance Rating"]]

        ]

        analytics_tbl = Table(
            analytics_table,
            colWidths=[3.8*inch, 2.2*inch]
        )

        analytics_tbl.setStyle(

            TableStyle([

                ("BACKGROUND",(0,0),(-1,0),colors.darkgreen),

                ("TEXTCOLOR",(0,0),(-1,0),colors.white),

                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

                ("ALIGN",(0,0),(-1,-1),"CENTER"),

                ("GRID",(0,0),(-1,-1),1,colors.black),

                ("BACKGROUND",(0,1),(-1,-1),colors.beige),

                ("BOTTOMPADDING",(0,0),(-1,0),10)

            ])

        )

        elements.append(analytics_tbl)

        elements.append(Spacer(1,0.35*inch))

        # =====================================================
        # AI CONCLUSION
        # =====================================================

        elements.append(
            Paragraph(
                "AI Conclusion",
                self.heading_style
            )
        )

        conclusion = f"""
<b>Traffic Status:</b> {report['Traffic Density']}<br/><br/>

The AI analyzed the uploaded traffic data using YOLOv8 object detection
and calculated congestion based on weighted vehicle categories.

The recommended green signal duration is
<b>{report['Recommended Green Time']} seconds</b>.

The estimated traffic efficiency after optimization is
<b>{analytics['Traffic Efficiency (%)']}%</b>.

Overall AI Performance Rating:
<b>{analytics['AI Performance Rating']}</b>.
"""

        elements.append(
            Paragraph(
                conclusion,
                self.normal_style
            )
        )

        elements.append(Spacer(1,0.40*inch))

        # =====================================================
        # FOOTER
        # =====================================================

        elements.append(

            Paragraph(

                "<font size=9 color='grey'>"
                "Generated by Synapse AI | "
                "Smart Traffic Management System | "
                "YOLOv8 + OpenCV + Python + Streamlit"
                "</font>",

                self.normal_style

            )

        )

        # =====================================================
        # BUILD PDF
        # =====================================================

        doc.build(elements)

        return pdf_path